version: "3.7"

services:
  app: 
    build: .
    command: node_modules/.bin/nodemon  --exec npm run dev -e ts,json
    environment:
      NODE_ENV: development
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules